version: "3"

services:
  opengrok:
    container_name: opengrok
    image: opengrok/docker:latest
    ports:
      - "${LOCAL_OPENGROK_PORT:-8080}:8080/tcp"
    environment:
      SYNC_PERIOD_MINUTES: '60'
    volumes:
       - './opengrok/src/:/opengrok/src/'  # source code
       - './opengrok/etc/:/opengrok/etc/'  # folder contains configuration.xml
       - './opengrok/data/:/opengrok/data/'  # index and other things for source codek